import { Alert, Button, Card, FileInput, Group, Loader, Stack, Text, TextInput, Title } from '@mantine/core';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuthStore } from '../../../shared/stores/auth.store.ts';
import { usePlugins, useSourceMutations } from '../hooks/sourceQueries.ts';

export function PluginManagementPage() {
  const navigate = useNavigate(); const admin = useAuthStore(state => state.verifiedUser?.role === 'admin'); const plugins = usePlugins(admin); const mutations = useSourceMutations();
  const [packageName, setPackageName] = useState(''); const [file, setFile] = useState<File | null>(null); const [trusted, setTrusted] = useState(false); const [error, setError] = useState('');
  if (!admin) return <Alert color="red">只有管理员可以管理插件。</Alert>; if (plugins.isPending) return <Loader />;
  const install = async () => { if (!trusted) { setError('请确认插件来源可信。'); return; } try { if (file) await mutations.uploadPlugin.mutateAsync(file); else if (packageName.trim()) await mutations.installPlugin.mutateAsync(packageName.trim()); else return; setPackageName(''); setFile(null); setTrusted(false); } catch (reason) { setError(reason instanceof Error ? reason.message : '插件安装失败'); } };
  return <Stack p="md" maw={950} mx="auto"><Group justify="space-between"><Title order={1}>插件管理</Title><Button variant="subtle" onClick={() => navigate('/sources')}>返回</Button></Group>{error && <Alert color="red">{error}</Alert>}<Card withBorder><Stack><Text fw={600}>安装插件</Text><TextInput label="npm 包名" placeholder="例如 reader-source-example" value={packageName} onChange={event => setPackageName(event.currentTarget.value)} /><FileInput label="或上传插件包" value={file} onChange={setFile} accept=".tgz,.zip,.js" /><label><input type="checkbox" checked={trusted} onChange={event => setTrusted(event.currentTarget.checked)} /> 我确认插件来源可信</label><Button onClick={() => void install()} loading={mutations.installPlugin.isPending || mutations.uploadPlugin.isPending}>安装并启用</Button></Stack></Card>{plugins.error && <Alert color="red">{plugins.error.message}</Alert>}{plugins.data?.map(plugin => <Card key={plugin.pluginId} withBorder><Group justify="space-between"><div><Text fw={600}>{plugin.name || plugin.pluginId}</Text><Text size="sm" c="dimmed">{plugin.version || '未知版本'} · {plugin.builtin ? '内置' : plugin.enabled ? '已启用' : '已停用'}</Text>{plugin.error && <Text c="red">{plugin.error.message}</Text>}</div><Group>{!plugin.builtin && <><Button size="compact-sm" loading={mutations.enablePlugin.isPending} onClick={() => mutations.enablePlugin.mutate({ id: plugin.pluginId, enabled: !plugin.enabled })}>{plugin.enabled ? '停用' : '启用'}</Button><Button size="compact-sm" color="red" variant="subtle" loading={mutations.uninstallPlugin.isPending} onClick={() => mutations.uninstallPlugin.mutate(plugin.pluginId)}>卸载</Button></>}</Group></Group></Card>)}</Stack>;
}
