/**
 * The icon font's code points.
 *
 * Generated by `tools/icons/build.mjs` from the same data that builds
 * `reader-icons.ttf`. Do not edit by hand: a code point that disagrees with the
 * font's `cmap` renders as a missing-glyph box, and nothing in the type system
 * can catch it.
 */
export const ICON_CODEPOINTS = {
  'bars': '\ue900',
  'chevron-left': '\ue901',
  'chevron-right': '\ue902',
  'arrow-left': '\ue903',
  'folder': '\ue904',
  'file-lines': '\ue905',
  'sliders': '\ue906',
  'magnifying-glass': '\ue907',
  'xmark': '\ue908',
  'plus': '\ue909',
  'check': '\ue90a',
  'file-arrow-up': '\ue90b',
  'trash-can': '\ue90c',
  'file-arrow-down': '\ue90d',
  'arrows-rotate': '\ue90e',
  'book': '\ue90f',
  'table-columns': '\ue910',
  'play': '\ue911',
  'pause': '\ue912',
  'backward-step': '\ue913',
  'forward-step': '\ue914',
  'stop': '\ue915',
  'volume-high': '\ue916',
  'moon': '\ue917',
  'sun': '\ue918',
  'eye': '\ue919',
  'circle-info': '\ue91a',
  'triangle-exclamation': '\ue91b',
  'clock': '\ue91c',
  'folder-open': '\ue91d',
  'ellipsis': '\ue91e',
  'pen': '\ue91f',
  'arrow-down-wide-short': '\ue920',
  'power-off': '\ue921',
  'right-from-bracket': '\ue922',
  'circle-plus': '\ue923',
  'indent': '\ue924',
  'font': '\ue925',
  'up-down': '\ue926',
  'gear': '\ue927',
  'books': '\ue928',
  'tune': '\ue929',
} as const;

export type IconName = keyof typeof ICON_CODEPOINTS;
