/**
 * The icon font's code points.
 *
 * Generated by `tools/icons/build.mjs` from the same data that builds
 * `reader-icons.ttf`. Do not edit by hand: a code point that disagrees with the
 * font's `cmap` renders as a missing-glyph box, and nothing in the type system
 * can catch it.
 */
export const ICON_CODEPOINTS = {
  'menu': '\ue900',
  'chevron-left': '\ue901',
  'chevron-right': '\ue902',
  'arrow-left': '\ue903',
  'folder': '\ue904',
  'file-text': '\ue905',
  'sliders': '\ue906',
  'search': '\ue907',
  'close': '\ue908',
  'plus': '\ue909',
  'check': '\ue90a',
  'upload': '\ue90b',
  'trash': '\ue90c',
  'download': '\ue90d',
  'refresh': '\ue90e',
  'book': '\ue90f',
  'shelf': '\ue910',
  'play': '\ue911',
  'pause': '\ue912',
  'step-backward': '\ue913',
  'step-forward': '\ue914',
  'stop': '\ue915',
  'volume': '\ue916',
  'moon': '\ue917',
  'sun': '\ue918',
  'eye': '\ue919',
  'info': '\ue91a',
  'warning': '\ue91b',
  'clock': '\ue91c',
  'more': '\ue91d',
  'edit': '\ue91e',
  'sort': '\ue91f',
  'logout': '\ue920',
  'sign-out': '\ue921',
  'add-circle': '\ue922',
  'indent': '\ue923',
  'text-size': '\ue924',
  'line-height': '\ue925',
  'settings': '\ue926',
  'library': '\ue927',
  'tune': '\ue928',
} as const;

export type IconName = keyof typeof ICON_CODEPOINTS;
