import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,basename} from 'node:path';
import {Db} from '../src/db/index.ts';
import {MediaLibraries} from '../src/media/libraries.ts';
import {MediaScanner} from '../src/media/scanner.ts';
test('album playback orders discs/tracks, follows rescanned tags and retains missing tracks',async t=>{
  const root=await mkdtemp(join(tmpdir(),'media-album-')),db=new Db(':memory:'),libraries=new MediaLibraries(db),actor={id:'admin',role:'admin'} as const;
  let changed=false;
  const scanner=new MediaScanner(db,libraries,async file=>({status:'ready',info:{duration:20,format:'mp3',streams:[],chapters:[],tags:{album:'专辑',artist:'歌手',title:basename(file),disc:basename(file)==='a.mp3'?'2':'1',track:basename(file)==='b.mp3'?(changed?'3':'1'):'2'}}}));
  t.after(async()=>{await scanner.close();db.close();await rm(root,{recursive:true,force:true});});
  for(const name of ['a.mp3','b.mp3','c.mp3'])await writeFile(join(root,name),name);
  const lib=await libraries.create(actor,{root,name:'music',kind:'music',access:'restricted'});
  const scan=async()=>{scanner.start(actor,lib.id);await scanner.wait(lib.id);};await scan();
  const catalog=scanner.catalog,album=catalog.list(actor,lib.id,{kind:'album'}).items[0]!;
  assert.deepEqual(catalog.albumPlayback(actor,album.id).tracks.map(track=>track.title),['b.mp3','c.mp3','a.mp3']);
  assert.throws(()=>catalog.albumPlayback({id:'member',role:'member'},album.id),{statusCode:404});
  assert.throws(()=>catalog.albumPlayback(actor,catalog.albumPlayback(actor,album.id).tracks[0]!.id),{code:'MEDIA_NOT_ALBUM'});
  changed=true;await writeFile(join(root,'b.mp3'),'changed');await scan();
  assert.deepEqual(catalog.albumPlayback(actor,album.id).tracks.map(track=>track.title),['c.mp3','b.mp3','a.mp3']);
  await rm(join(root,'c.mp3'));await scan();
  assert.equal(catalog.albumPlayback(actor,album.id).tracks[0]!.editions[0]!.parts[0]!.available,false);
  const before=catalog.albumPlayback(actor,album.id).tracks,source=before[2]!;
  const created=catalog.createEditionItem(actor,source.editions[0]!.id,'新建曲目',source.id);
  assert.equal(created.parentId,album.id);assert.equal(created.metadata.disc,2);assert.equal(created.metadata.track,2);
  const after=catalog.albumPlayback(actor,album.id).tracks;
  assert.deepEqual(after.map(track=>track.title),['c.mp3','b.mp3','新建曲目']);
  assert.equal(after[0]!.editions[0]!.parts[0]!.available,false,'missing files remain in playback plans');
  assert.equal(catalog.detail(actor,source.id).editions.length,0,'the old catalog entry is preserved');
  await writeFile(join(root,'a.mp3'),'new bytes');await scan();
  assert.deepEqual(catalog.albumPlayback(actor,album.id).tracks.map(track=>track.title),['c.mp3','b.mp3','新建曲目']);
});
