import { render } from '../src/shared/ui/render-root.ts';
// @vitest-environment jsdom
import { afterEach, expect, it, vi } from 'vitest';
import { act } from 'react';

import { MediaSearch, searchReturnFor } from '../src/features/media/components/search.tsx';
import type { MediaApi, SearchItem } from '../src/features/media/api/media-api.ts';

const root=document.createElement('div');root.className='media-screen';document.body.append(root);
afterEach(()=>{act(()=>render(null,root));root.scrollTop=0;});
it('filters by scope, restores pagination on return, and resets it when switching scope',async()=>{
  const item:SearchItem={id:'track',libraryId:'lib',title:'目标曲目',kind:'track',channel:'music',libraryName:'音乐',parentId:null,metadata:{},overrides:{}};
  const search=vi.fn(async(_query:string,_scope:string,_offset:number,_signal?:AbortSignal,_kind?:string)=>({items:[item],total:61}));
  const api={preferenceScope:()=> 'filter-account',search} as unknown as MediaApi;
  const mount=()=>render(<MediaSearch api={api} channel="music" navigate={()=>{}}/>,root);
  await act(async()=>mount());
  await act(async()=>{const input=root.querySelector('input')!;input.value='目标';input.dispatchEvent(new Event('input',{bubbles:true}));});
  await act(async()=>{root.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});
  expect(root.querySelector('[aria-label="内容类型"]')).toBeNull();
  await vi.waitFor(()=>expect([...root.querySelectorAll('button')].find(button=>button.textContent==='下一页')?.disabled).toBe(false));
  await act(async()=>[...root.querySelectorAll('button')].find(button=>button.textContent==='下一页')!.click());
  await vi.waitFor(()=>expect(search.mock.calls.at(-1)?.[2]).toBe(60));
  await vi.waitFor(()=>expect(root.querySelector('.media-search-result')).not.toBeNull());
  await act(async()=>root.querySelector<HTMLButtonElement>('.media-search-result')!.click());
  expect(searchReturnFor(api)).toMatchObject({scope:'music',offset:60});
  act(()=>render(null,root));await act(async()=>mount());
  expect(root.querySelector('[data-scope=music]')!.getAttribute('aria-pressed')).toBe('true');
  await act(async()=>{root.querySelector<HTMLButtonElement>('[data-scope=video]')!.click();});
  await vi.waitFor(()=>expect(search.mock.calls.at(-1)?.slice(0,3)).toEqual(['目标','video',0]));
  expect(search.mock.calls.at(-1)?.[4]).toBeUndefined();
});
it('restores a cross-channel search on return and does not restore another account’s query',async()=>{
  let identity='account-a';
  const item:SearchItem={id:'film',libraryId:'lib',title:'测试电影',kind:'movie',channel:'video',libraryName:'电影库',parentId:null,metadata:{},overrides:{}};
  const search=vi.fn(async()=>({items:[item],total:1}));
  const api={search,preferenceScope:()=>identity} as unknown as MediaApi;
  const mount=()=>render(<MediaSearch api={api} channel="music" navigate={()=>{}}/>,root);
  await act(async()=>mount());
  await act(async()=>{const input=root.querySelector('input')!;input.value='电影';input.dispatchEvent(new Event('input',{bubbles:true}));root.querySelector<HTMLButtonElement>('[data-scope=all]')!.click();});
  await act(async()=>{root.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});
  await vi.waitFor(()=>expect(root.querySelector('.media-search-result')).not.toBeNull());
  root.scrollTop=420;
  await act(async()=>root.querySelector<HTMLButtonElement>('.media-search-result')!.click());
  expect(searchReturnFor(api)).toMatchObject({channel:'music',targetChannel:'video',itemId:'film',query:'电影',scope:'all'});
  act(()=>render(null,root));root.scrollTop=0;await act(async()=>mount());
  expect(root.querySelector('input')!.value).toBe('电影');expect(root.querySelector('[data-scope=all]')!.getAttribute('aria-pressed')).toBe('true');
  await vi.waitFor(()=>expect(search).toHaveBeenCalledTimes(2));
  await vi.waitFor(()=>expect(root.scrollTop).toBe(420));
  act(()=>render(null,root));identity='account-b';await act(async()=>mount());
  expect(root.querySelector('input')!.value).toBe('');expect(searchReturnFor(api)).toBeUndefined();
});
it.each([false,true])('recovers an invalid search page without a false empty result (failure=%s)',async(failRecovery)=>{
  const item:SearchItem={id:'track',libraryId:'lib',title:'保留的结果',kind:'track',channel:'music',libraryName:'音乐',parentId:null,metadata:{},overrides:{}};
  const search=vi.fn().mockResolvedValueOnce({items:[item],total:61}).mockResolvedValueOnce({items:[],total:1});
  const onLocationChange=vi.fn();
  if(failRecovery)search.mockRejectedValueOnce(new Error('恢复页读取失败'));
  else search.mockResolvedValueOnce({items:[item],total:1});
  await act(async()=>render(<MediaSearch api={{preferenceScope:()=> 'test',search} as unknown as MediaApi} channel="music" onLocationChange={onLocationChange} navigate={()=>{}}/>,root));
  await act(async()=>{const input=root.querySelector('input')!;input.value='保留';input.dispatchEvent(new Event('input',{bubbles:true}));});
  await act(async()=>{root.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});
  await vi.waitFor(()=>expect(root.querySelector('.media-search-result')).not.toBeNull());
  await act(async()=>[...root.querySelectorAll('button')].find(button=>button.textContent==='下一页')!.click());
  await vi.waitFor(()=>expect(search).toHaveBeenCalledTimes(3));
  expect(search.mock.calls.map(call=>call.slice(0,3))).toEqual([['保留','music',0],['保留','music',60],['保留','music',0]]);
  await vi.waitFor(()=>expect(root.textContent).toContain(failRecovery?'恢复页读取失败':'保留的结果'));
  expect(root.textContent).not.toContain('没有匹配内容');
  expect(root.querySelector('input')!.value).toBe('保留');
  expect(onLocationChange).toHaveBeenLastCalledWith({q:'保留',scope:'music',offset:'0'});
});
it('distinguishes same-title results with available credits and manual year overrides',async()=>{
  const base={id:'film',libraryId:'lib',title:'同名作品',kind:'movie',channel:'video',libraryName:'媒体库',parentId:null,metadata:{year:1990},overrides:{year:2024}} as SearchItem;
  const items:SearchItem[]=[base,{...base,id:'track',kind:'track',channel:'music',metadata:{artist:'演唱者'},overrides:{}},{...base,id:'audio',kind:'audiobook',channel:'audiobook',metadata:{author:'作者甲',narrator:'演播乙'},overrides:{}},{...base,id:'empty',metadata:{},overrides:{}}];
  await act(async()=>render(<MediaSearch api={{preferenceScope:()=> 'test',search:async()=>({items,total:items.length})} as unknown as MediaApi} channel="music" navigate={()=>{}}/>,root));
  await act(async()=>{const input=root.querySelector('input')!;input.value='同名';input.dispatchEvent(new Event('input',{bubbles:true}));});
  await act(async()=>{root.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});
  await vi.waitFor(()=>expect(root.querySelectorAll('.media-search-result')).toHaveLength(4));
  expect([...root.querySelectorAll('.media-search-description')].map(node=>node.textContent)).toEqual(['2024','演唱者','作者 作者甲 · 演播 演播乙']);
  expect([...root.querySelectorAll('.media-search-result')].filter(node=>!node.querySelector('.media-search-description'))).toHaveLength(1);
});
it('switches scope, ignores late results, and navigates to the result channel',async()=>{
  const pending:Array<{resolve:(value:{items:SearchItem[];total:number})=>void;signal:AbortSignal}>=[];
  const search=vi.fn((_query,_scope,_offset,signal)=>new Promise(resolve=>pending.push({resolve,signal})));
  const navigate=vi.fn();
  await act(async()=>render(<MediaSearch api={{preferenceScope:()=> 'test',search} as unknown as MediaApi} channel="music" navigate={navigate}/>,root));
  expect(search).not.toHaveBeenCalled();
  await act(async()=>{const input=root.querySelector('input')!;input.value='测试';input.dispatchEvent(new Event('input',{bubbles:true}));});
  await act(async()=>{root.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});
  expect(search.mock.calls[0]!.slice(0,3)).toEqual(['测试','music',0]);
  await act(async()=>{root.querySelector<HTMLButtonElement>('[data-scope=all]')!.click();});
  expect(pending[0]!.signal.aborted).toBe(true);
  const item:SearchItem={id:'film',libraryId:'lib',title:'测试电影',kind:'movie',channel:'video',libraryName:'电影库',parentId:null,metadata:{},overrides:{}};
  await act(async()=>pending[1]!.resolve({items:[item],total:1}));
  await act(async()=>pending[0]!.resolve({items:[],total:0}));
  expect(root.textContent).toContain('测试电影');
  await act(async()=>root.querySelector<HTMLButtonElement>('.media-search-result')!.click());
  expect(navigate).toHaveBeenCalledWith('video','film');
  act(()=>render(null,root));
  expect(pending[1]!.signal.aborted).toBe(true);
});

it('updates the route only on explicit actions and never on mounting or unmounting',async()=>{
  const onLocationChange=vi.fn(),search=vi.fn().mockResolvedValue({items:[],total:0});
  await act(async()=>render(<MediaSearch api={{preferenceScope:()=> 'route',search} as unknown as MediaApi} channel="video" initialLocation={{q:'test',kind:'movie'}} onLocationChange={onLocationChange} navigate={()=>{}}/>,root));
  await vi.waitFor(()=>expect(search).toHaveBeenCalled());
  expect(search.mock.calls[0]!.slice(0,3)).toEqual(['test','all',0]);
  expect(search.mock.calls[0]![4]).toBeUndefined();
  expect(onLocationChange).not.toHaveBeenCalled();
  await act(async()=>root.querySelector<HTMLButtonElement>('[data-scope=music]')!.click());
  expect(onLocationChange).toHaveBeenCalledTimes(1);
  expect(onLocationChange).toHaveBeenLastCalledWith({q:'test',scope:'music',offset:'0'});
  await act(async()=>render(null,root));
  expect(onLocationChange).toHaveBeenCalledTimes(1);
});
